# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TensionUI_LRG.ui'
#
# Created: Thu Nov  3 09:21:58 2016
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 1017)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setCursor(QtCore.Qt.CrossCursor)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UA1 = QtGui.QLineEdit(self.centralwidget)
        self.UA1.setGeometry(QtCore.QRect(74, 50, 40, 25))
        self.UA1.setMaxLength(2)
        self.UA1.setObjectName("UA1")
        self.UB1 = QtGui.QLineEdit(self.centralwidget)
        self.UB1.setGeometry(QtCore.QRect(154, 50, 40, 25))
        self.UB1.setMaxLength(2)
        self.UB1.setObjectName("UB1")
        self.VA1 = QtGui.QLineEdit(self.centralwidget)
        self.VA1.setGeometry(QtCore.QRect(410, 50, 40, 25))
        self.VA1.setMaxLength(2)
        self.VA1.setObjectName("VA1")
        self.VB1 = QtGui.QLineEdit(self.centralwidget)
        self.VB1.setGeometry(QtCore.QRect(330, 50, 40, 25))
        self.VB1.setMaxLength(2)
        self.VB1.setObjectName("VB1")
        self.UB2 = QtGui.QLineEdit(self.centralwidget)
        self.UB2.setGeometry(QtCore.QRect(154, 77, 40, 25))
        self.UB2.setMaxLength(2)
        self.UB2.setObjectName("UB2")
        self.VB2 = QtGui.QLineEdit(self.centralwidget)
        self.VB2.setGeometry(QtCore.QRect(330, 77, 40, 25))
        self.VB2.setMaxLength(2)
        self.VB2.setObjectName("VB2")
        self.UA2 = QtGui.QLineEdit(self.centralwidget)
        self.UA2.setGeometry(QtCore.QRect(74, 77, 40, 25))
        self.UA2.setMaxLength(2)
        self.UA2.setObjectName("UA2")
        self.VA2 = QtGui.QLineEdit(self.centralwidget)
        self.VA2.setGeometry(QtCore.QRect(410, 77, 40, 25))
        self.VA2.setMaxLength(2)
        self.VA2.setObjectName("VA2")
        self.UB3 = QtGui.QLineEdit(self.centralwidget)
        self.UB3.setGeometry(QtCore.QRect(154, 104, 40, 25))
        self.UB3.setMaxLength(2)
        self.UB3.setObjectName("UB3")
        self.VB3 = QtGui.QLineEdit(self.centralwidget)
        self.VB3.setGeometry(QtCore.QRect(330, 104, 40, 25))
        self.VB3.setMaxLength(2)
        self.VB3.setObjectName("VB3")
        self.VB4 = QtGui.QLineEdit(self.centralwidget)
        self.VB4.setGeometry(QtCore.QRect(330, 131, 40, 25))
        self.VB4.setMaxLength(2)
        self.VB4.setObjectName("VB4")
        self.VA4 = QtGui.QLineEdit(self.centralwidget)
        self.VA4.setGeometry(QtCore.QRect(410, 131, 40, 25))
        self.VA4.setMaxLength(2)
        self.VA4.setObjectName("VA4")
        self.UB4 = QtGui.QLineEdit(self.centralwidget)
        self.UB4.setGeometry(QtCore.QRect(154, 131, 40, 25))
        self.UB4.setMaxLength(2)
        self.UB4.setObjectName("UB4")
        self.UA3 = QtGui.QLineEdit(self.centralwidget)
        self.UA3.setGeometry(QtCore.QRect(74, 104, 40, 25))
        self.UA3.setMaxLength(2)
        self.UA3.setObjectName("UA3")
        self.UA4 = QtGui.QLineEdit(self.centralwidget)
        self.UA4.setGeometry(QtCore.QRect(74, 131, 40, 25))
        self.UA4.setMaxLength(2)
        self.UA4.setObjectName("UA4")
        self.VA3 = QtGui.QLineEdit(self.centralwidget)
        self.VA3.setGeometry(QtCore.QRect(410, 104, 40, 25))
        self.VA3.setMaxLength(2)
        self.VA3.setObjectName("VA3")
        self.UB5 = QtGui.QLineEdit(self.centralwidget)
        self.UB5.setGeometry(QtCore.QRect(154, 159, 40, 25))
        self.UB5.setMaxLength(2)
        self.UB5.setObjectName("UB5")
        self.UA7 = QtGui.QLineEdit(self.centralwidget)
        self.UA7.setGeometry(QtCore.QRect(74, 216, 40, 25))
        self.UA7.setMaxLength(2)
        self.UA7.setObjectName("UA7")
        self.VB5 = QtGui.QLineEdit(self.centralwidget)
        self.VB5.setGeometry(QtCore.QRect(330, 159, 40, 25))
        self.VB5.setMaxLength(2)
        self.VB5.setObjectName("VB5")
        self.VB6 = QtGui.QLineEdit(self.centralwidget)
        self.VB6.setGeometry(QtCore.QRect(330, 187, 40, 25))
        self.VB6.setMaxLength(2)
        self.VB6.setObjectName("VB6")
        self.VA7 = QtGui.QLineEdit(self.centralwidget)
        self.VA7.setGeometry(QtCore.QRect(410, 216, 40, 25))
        self.VA7.setMaxLength(2)
        self.VA7.setObjectName("VA7")
        self.VA6 = QtGui.QLineEdit(self.centralwidget)
        self.VA6.setGeometry(QtCore.QRect(410, 187, 40, 25))
        self.VA6.setMaxLength(2)
        self.VA6.setObjectName("VA6")
        self.UB6 = QtGui.QLineEdit(self.centralwidget)
        self.UB6.setGeometry(QtCore.QRect(154, 187, 40, 25))
        self.UB6.setMaxLength(2)
        self.UB6.setObjectName("UB6")
        self.UA5 = QtGui.QLineEdit(self.centralwidget)
        self.UA5.setGeometry(QtCore.QRect(74, 159, 40, 25))
        self.UA5.setMaxLength(2)
        self.UA5.setObjectName("UA5")
        self.VB7 = QtGui.QLineEdit(self.centralwidget)
        self.VB7.setGeometry(QtCore.QRect(330, 216, 40, 25))
        self.VB7.setMaxLength(2)
        self.VB7.setObjectName("VB7")
        self.UB8 = QtGui.QLineEdit(self.centralwidget)
        self.UB8.setGeometry(QtCore.QRect(154, 243, 40, 25))
        self.UB8.setMaxLength(2)
        self.UB8.setObjectName("UB8")
        self.VB8 = QtGui.QLineEdit(self.centralwidget)
        self.VB8.setGeometry(QtCore.QRect(330, 243, 40, 25))
        self.VB8.setMaxLength(2)
        self.VB8.setObjectName("VB8")
        self.UA6 = QtGui.QLineEdit(self.centralwidget)
        self.UA6.setGeometry(QtCore.QRect(74, 187, 40, 25))
        self.UA6.setMaxLength(2)
        self.UA6.setObjectName("UA6")
        self.UB7 = QtGui.QLineEdit(self.centralwidget)
        self.UB7.setGeometry(QtCore.QRect(154, 216, 40, 25))
        self.UB7.setMaxLength(2)
        self.UB7.setObjectName("UB7")
        self.VA8 = QtGui.QLineEdit(self.centralwidget)
        self.VA8.setGeometry(QtCore.QRect(410, 243, 40, 25))
        self.VA8.setMaxLength(2)
        self.VA8.setObjectName("VA8")
        self.VA5 = QtGui.QLineEdit(self.centralwidget)
        self.VA5.setGeometry(QtCore.QRect(410, 159, 40, 25))
        self.VA5.setMaxLength(2)
        self.VA5.setObjectName("VA5")
        self.UA8 = QtGui.QLineEdit(self.centralwidget)
        self.UA8.setGeometry(QtCore.QRect(74, 243, 40, 25))
        self.UA8.setMaxLength(2)
        self.UA8.setObjectName("UA8")
        self.VB12 = QtGui.QLineEdit(self.centralwidget)
        self.VB12.setGeometry(QtCore.QRect(330, 354, 40, 25))
        self.VB12.setMaxLength(2)
        self.VB12.setObjectName("VB12")
        self.UB14 = QtGui.QLineEdit(self.centralwidget)
        self.UB14.setGeometry(QtCore.QRect(154, 409, 40, 25))
        self.UB14.setMaxLength(2)
        self.UB14.setObjectName("UB14")
        self.UA12 = QtGui.QLineEdit(self.centralwidget)
        self.UA12.setGeometry(QtCore.QRect(74, 354, 40, 25))
        self.UA12.setMaxLength(2)
        self.UA12.setObjectName("UA12")
        self.VB13 = QtGui.QLineEdit(self.centralwidget)
        self.VB13.setGeometry(QtCore.QRect(330, 382, 40, 25))
        self.VB13.setMaxLength(2)
        self.VB13.setObjectName("VB13")
        self.VA13 = QtGui.QLineEdit(self.centralwidget)
        self.VA13.setGeometry(QtCore.QRect(410, 382, 40, 25))
        self.VA13.setMaxLength(2)
        self.VA13.setObjectName("VA13")
        self.VB9 = QtGui.QLineEdit(self.centralwidget)
        self.VB9.setGeometry(QtCore.QRect(330, 270, 40, 25))
        self.VB9.setMaxLength(2)
        self.VB9.setObjectName("VB9")
        self.UA9 = QtGui.QLineEdit(self.centralwidget)
        self.UA9.setGeometry(QtCore.QRect(74, 270, 40, 25))
        self.UA9.setMaxLength(2)
        self.UA9.setObjectName("UA9")
        self.UA10 = QtGui.QLineEdit(self.centralwidget)
        self.UA10.setGeometry(QtCore.QRect(74, 298, 40, 25))
        self.UA10.setMaxLength(2)
        self.UA10.setObjectName("UA10")
        self.VB11 = QtGui.QLineEdit(self.centralwidget)
        self.VB11.setGeometry(QtCore.QRect(330, 325, 40, 25))
        self.VB11.setMaxLength(2)
        self.VB11.setObjectName("VB11")
        self.VB10 = QtGui.QLineEdit(self.centralwidget)
        self.VB10.setGeometry(QtCore.QRect(330, 298, 40, 25))
        self.VB10.setMaxLength(2)
        self.VB10.setObjectName("VB10")
        self.UA15 = QtGui.QLineEdit(self.centralwidget)
        self.UA15.setGeometry(QtCore.QRect(74, 438, 40, 25))
        self.UA15.setMaxLength(2)
        self.UA15.setObjectName("UA15")
        self.VA15 = QtGui.QLineEdit(self.centralwidget)
        self.VA15.setGeometry(QtCore.QRect(410, 438, 40, 25))
        self.VA15.setMaxLength(2)
        self.VA15.setObjectName("VA15")
        self.UA11 = QtGui.QLineEdit(self.centralwidget)
        self.UA11.setGeometry(QtCore.QRect(74, 325, 40, 25))
        self.UA11.setMaxLength(2)
        self.UA11.setObjectName("UA11")
        self.VA16 = QtGui.QLineEdit(self.centralwidget)
        self.VA16.setGeometry(QtCore.QRect(410, 466, 40, 25))
        self.VA16.setMaxLength(2)
        self.VA16.setObjectName("VA16")
        self.UB13 = QtGui.QLineEdit(self.centralwidget)
        self.UB13.setGeometry(QtCore.QRect(154, 382, 40, 25))
        self.UB13.setMaxLength(2)
        self.UB13.setObjectName("UB13")
        self.UA16 = QtGui.QLineEdit(self.centralwidget)
        self.UA16.setGeometry(QtCore.QRect(74, 466, 40, 25))
        self.UA16.setMaxLength(2)
        self.UA16.setObjectName("UA16")
        self.UB11 = QtGui.QLineEdit(self.centralwidget)
        self.UB11.setGeometry(QtCore.QRect(154, 325, 40, 25))
        self.UB11.setMaxLength(2)
        self.UB11.setObjectName("UB11")
        self.VA14 = QtGui.QLineEdit(self.centralwidget)
        self.VA14.setGeometry(QtCore.QRect(410, 409, 40, 25))
        self.VA14.setMaxLength(2)
        self.VA14.setObjectName("VA14")
        self.VB16 = QtGui.QLineEdit(self.centralwidget)
        self.VB16.setGeometry(QtCore.QRect(330, 466, 40, 25))
        self.VB16.setMaxLength(2)
        self.VB16.setObjectName("VB16")
        self.VA11 = QtGui.QLineEdit(self.centralwidget)
        self.VA11.setGeometry(QtCore.QRect(410, 325, 40, 25))
        self.VA11.setMaxLength(2)
        self.VA11.setObjectName("VA11")
        self.UB15 = QtGui.QLineEdit(self.centralwidget)
        self.UB15.setGeometry(QtCore.QRect(154, 438, 40, 25))
        self.UB15.setMaxLength(2)
        self.UB15.setObjectName("UB15")
        self.UB9 = QtGui.QLineEdit(self.centralwidget)
        self.UB9.setGeometry(QtCore.QRect(154, 270, 40, 25))
        self.UB9.setMaxLength(2)
        self.UB9.setObjectName("UB9")
        self.UB16 = QtGui.QLineEdit(self.centralwidget)
        self.UB16.setGeometry(QtCore.QRect(154, 466, 40, 25))
        self.UB16.setMaxLength(2)
        self.UB16.setObjectName("UB16")
        self.VA9 = QtGui.QLineEdit(self.centralwidget)
        self.VA9.setGeometry(QtCore.QRect(410, 270, 40, 25))
        self.VA9.setMaxLength(2)
        self.VA9.setObjectName("VA9")
        self.UA13 = QtGui.QLineEdit(self.centralwidget)
        self.UA13.setGeometry(QtCore.QRect(74, 382, 40, 25))
        self.UA13.setMaxLength(2)
        self.UA13.setObjectName("UA13")
        self.VA12 = QtGui.QLineEdit(self.centralwidget)
        self.VA12.setGeometry(QtCore.QRect(410, 354, 40, 25))
        self.VA12.setMaxLength(2)
        self.VA12.setObjectName("VA12")
        self.UA14 = QtGui.QLineEdit(self.centralwidget)
        self.UA14.setGeometry(QtCore.QRect(74, 409, 40, 25))
        self.UA14.setMaxLength(2)
        self.UA14.setObjectName("UA14")
        self.VA10 = QtGui.QLineEdit(self.centralwidget)
        self.VA10.setGeometry(QtCore.QRect(410, 298, 40, 25))
        self.VA10.setMaxLength(2)
        self.VA10.setObjectName("VA10")
        self.VB14 = QtGui.QLineEdit(self.centralwidget)
        self.VB14.setGeometry(QtCore.QRect(330, 409, 40, 25))
        self.VB14.setMaxLength(2)
        self.VB14.setObjectName("VB14")
        self.VB15 = QtGui.QLineEdit(self.centralwidget)
        self.VB15.setGeometry(QtCore.QRect(330, 438, 40, 25))
        self.VB15.setMaxLength(2)
        self.VB15.setObjectName("VB15")
        self.UB10 = QtGui.QLineEdit(self.centralwidget)
        self.UB10.setGeometry(QtCore.QRect(154, 298, 40, 25))
        self.UB10.setMaxLength(2)
        self.UB10.setObjectName("UB10")
        self.UB12 = QtGui.QLineEdit(self.centralwidget)
        self.UB12.setGeometry(QtCore.QRect(154, 354, 40, 25))
        self.UB12.setMaxLength(2)
        self.UB12.setObjectName("UB12")
        self.VA21 = QtGui.QLineEdit(self.centralwidget)
        self.VA21.setGeometry(QtCore.QRect(410, 603, 40, 25))
        self.VA21.setMaxLength(2)
        self.VA21.setObjectName("VA21")
        self.UA26 = QtGui.QLineEdit(self.centralwidget)
        self.UA26.setGeometry(QtCore.QRect(74, 742, 40, 25))
        self.UA26.setMaxLength(2)
        self.UA26.setObjectName("UA26")
        self.UB32 = QtGui.QLineEdit(self.centralwidget)
        self.UB32.setGeometry(QtCore.QRect(154, 909, 40, 25))
        self.UB32.setMaxLength(2)
        self.UB32.setObjectName("UB32")
        self.UA32 = QtGui.QLineEdit(self.centralwidget)
        self.UA32.setGeometry(QtCore.QRect(74, 909, 40, 25))
        self.UA32.setMaxLength(2)
        self.UA32.setObjectName("UA32")
        self.VB21 = QtGui.QLineEdit(self.centralwidget)
        self.VB21.setGeometry(QtCore.QRect(330, 603, 40, 25))
        self.VB21.setMaxLength(2)
        self.VB21.setObjectName("VB21")
        self.VB25 = QtGui.QLineEdit(self.centralwidget)
        self.VB25.setGeometry(QtCore.QRect(330, 714, 40, 25))
        self.VB25.setMaxLength(2)
        self.VB25.setObjectName("VB25")
        self.UB22 = QtGui.QLineEdit(self.centralwidget)
        self.UB22.setGeometry(QtCore.QRect(154, 630, 40, 25))
        self.UB22.setMaxLength(2)
        self.UB22.setObjectName("UB22")
        self.UB17 = QtGui.QLineEdit(self.centralwidget)
        self.UB17.setGeometry(QtCore.QRect(154, 493, 40, 25))
        self.UB17.setMaxLength(2)
        self.UB17.setObjectName("UB17")
        self.UB25 = QtGui.QLineEdit(self.centralwidget)
        self.UB25.setGeometry(QtCore.QRect(154, 714, 40, 25))
        self.UB25.setMaxLength(2)
        self.UB25.setObjectName("UB25")
        self.VA25 = QtGui.QLineEdit(self.centralwidget)
        self.VA25.setGeometry(QtCore.QRect(410, 714, 40, 25))
        self.VA25.setMaxLength(2)
        self.VA25.setObjectName("VA25")
        self.UB29 = QtGui.QLineEdit(self.centralwidget)
        self.UB29.setGeometry(QtCore.QRect(154, 827, 40, 25))
        self.UB29.setMaxLength(2)
        self.UB29.setObjectName("UB29")
        self.VA28 = QtGui.QLineEdit(self.centralwidget)
        self.VA28.setGeometry(QtCore.QRect(410, 799, 40, 25))
        self.VA28.setMaxLength(2)
        self.VA28.setObjectName("VA28")
        self.UA23 = QtGui.QLineEdit(self.centralwidget)
        self.UA23.setGeometry(QtCore.QRect(74, 658, 40, 25))
        self.UA23.setMaxLength(2)
        self.UA23.setObjectName("UA23")
        self.VA20 = QtGui.QLineEdit(self.centralwidget)
        self.VA20.setGeometry(QtCore.QRect(410, 576, 40, 25))
        self.VA20.setMaxLength(2)
        self.VA20.setObjectName("VA20")
        self.VB18 = QtGui.QLineEdit(self.centralwidget)
        self.VB18.setGeometry(QtCore.QRect(330, 520, 40, 25))
        self.VB18.setMaxLength(2)
        self.VB18.setObjectName("VB18")
        self.VA23 = QtGui.QLineEdit(self.centralwidget)
        self.VA23.setGeometry(QtCore.QRect(410, 658, 40, 25))
        self.VA23.setMaxLength(2)
        self.VA23.setObjectName("VA23")
        self.UB24 = QtGui.QLineEdit(self.centralwidget)
        self.UB24.setGeometry(QtCore.QRect(154, 686, 40, 25))
        self.UB24.setMaxLength(2)
        self.UB24.setObjectName("UB24")
        self.UB20 = QtGui.QLineEdit(self.centralwidget)
        self.UB20.setGeometry(QtCore.QRect(154, 576, 40, 25))
        self.UB20.setMaxLength(2)
        self.UB20.setObjectName("UB20")
        self.UA29 = QtGui.QLineEdit(self.centralwidget)
        self.UA29.setGeometry(QtCore.QRect(74, 827, 40, 25))
        self.UA29.setMaxLength(2)
        self.UA29.setObjectName("UA29")
        self.UA19 = QtGui.QLineEdit(self.centralwidget)
        self.UA19.setGeometry(QtCore.QRect(74, 548, 40, 25))
        self.UA19.setMaxLength(2)
        self.UA19.setObjectName("UA19")
        self.UB31 = QtGui.QLineEdit(self.centralwidget)
        self.UB31.setGeometry(QtCore.QRect(154, 881, 40, 25))
        self.UB31.setMaxLength(2)
        self.UB31.setObjectName("UB31")
        self.UB30 = QtGui.QLineEdit(self.centralwidget)
        self.UB30.setGeometry(QtCore.QRect(154, 854, 40, 25))
        self.UB30.setMaxLength(2)
        self.UB30.setObjectName("UB30")
        self.UB28 = QtGui.QLineEdit(self.centralwidget)
        self.UB28.setGeometry(QtCore.QRect(154, 799, 40, 25))
        self.UB28.setMaxLength(2)
        self.UB28.setObjectName("UB28")
        self.VB27 = QtGui.QLineEdit(self.centralwidget)
        self.VB27.setGeometry(QtCore.QRect(330, 770, 40, 25))
        self.VB27.setMaxLength(2)
        self.VB27.setObjectName("VB27")
        self.UA27 = QtGui.QLineEdit(self.centralwidget)
        self.UA27.setGeometry(QtCore.QRect(74, 770, 40, 25))
        self.UA27.setMaxLength(2)
        self.UA27.setObjectName("UA27")
        self.UA28 = QtGui.QLineEdit(self.centralwidget)
        self.UA28.setGeometry(QtCore.QRect(74, 799, 40, 25))
        self.UA28.setMaxLength(2)
        self.UA28.setObjectName("UA28")
        self.VA29 = QtGui.QLineEdit(self.centralwidget)
        self.VA29.setGeometry(QtCore.QRect(410, 827, 40, 25))
        self.VA29.setMaxLength(2)
        self.VA29.setObjectName("VA29")
        self.UA25 = QtGui.QLineEdit(self.centralwidget)
        self.UA25.setGeometry(QtCore.QRect(74, 714, 40, 25))
        self.UA25.setMaxLength(2)
        self.UA25.setObjectName("UA25")
        self.UA24 = QtGui.QLineEdit(self.centralwidget)
        self.UA24.setGeometry(QtCore.QRect(74, 686, 40, 25))
        self.UA24.setMaxLength(2)
        self.UA24.setObjectName("UA24")
        self.UB18 = QtGui.QLineEdit(self.centralwidget)
        self.UB18.setGeometry(QtCore.QRect(154, 520, 40, 25))
        self.UB18.setMaxLength(2)
        self.UB18.setObjectName("UB18")
        self.VA26 = QtGui.QLineEdit(self.centralwidget)
        self.VA26.setGeometry(QtCore.QRect(410, 742, 40, 25))
        self.VA26.setMaxLength(2)
        self.VA26.setObjectName("VA26")
        self.UA20 = QtGui.QLineEdit(self.centralwidget)
        self.UA20.setGeometry(QtCore.QRect(74, 576, 40, 25))
        self.UA20.setMaxLength(2)
        self.UA20.setObjectName("UA20")
        self.UA18 = QtGui.QLineEdit(self.centralwidget)
        self.UA18.setGeometry(QtCore.QRect(74, 520, 40, 25))
        self.UA18.setMaxLength(2)
        self.UA18.setObjectName("UA18")
        self.UA31 = QtGui.QLineEdit(self.centralwidget)
        self.UA31.setGeometry(QtCore.QRect(74, 881, 40, 25))
        self.UA31.setMaxLength(2)
        self.UA31.setObjectName("UA31")
        self.VA32 = QtGui.QLineEdit(self.centralwidget)
        self.VA32.setGeometry(QtCore.QRect(410, 909, 40, 25))
        self.VA32.setMaxLength(2)
        self.VA32.setObjectName("VA32")
        self.VB31 = QtGui.QLineEdit(self.centralwidget)
        self.VB31.setGeometry(QtCore.QRect(330, 881, 40, 25))
        self.VB31.setMaxLength(2)
        self.VB31.setObjectName("VB31")
        self.VB28 = QtGui.QLineEdit(self.centralwidget)
        self.VB28.setGeometry(QtCore.QRect(330, 799, 40, 25))
        self.VB28.setMaxLength(2)
        self.VB28.setObjectName("VB28")
        self.UA21 = QtGui.QLineEdit(self.centralwidget)
        self.UA21.setGeometry(QtCore.QRect(74, 603, 40, 25))
        self.UA21.setMaxLength(2)
        self.UA21.setObjectName("UA21")
        self.VA22 = QtGui.QLineEdit(self.centralwidget)
        self.VA22.setGeometry(QtCore.QRect(410, 630, 40, 25))
        self.VA22.setMaxLength(2)
        self.VA22.setObjectName("VA22")
        self.VB22 = QtGui.QLineEdit(self.centralwidget)
        self.VB22.setGeometry(QtCore.QRect(330, 630, 40, 25))
        self.VB22.setMaxLength(2)
        self.VB22.setObjectName("VB22")
        self.UA30 = QtGui.QLineEdit(self.centralwidget)
        self.UA30.setGeometry(QtCore.QRect(74, 854, 40, 25))
        self.UA30.setMaxLength(2)
        self.UA30.setObjectName("UA30")
        self.UB26 = QtGui.QLineEdit(self.centralwidget)
        self.UB26.setGeometry(QtCore.QRect(154, 742, 40, 25))
        self.UB26.setMaxLength(2)
        self.UB26.setObjectName("UB26")
        self.VA18 = QtGui.QLineEdit(self.centralwidget)
        self.VA18.setGeometry(QtCore.QRect(410, 520, 40, 25))
        self.VA18.setMaxLength(2)
        self.VA18.setObjectName("VA18")
        self.VA17 = QtGui.QLineEdit(self.centralwidget)
        self.VA17.setGeometry(QtCore.QRect(410, 493, 40, 25))
        self.VA17.setMaxLength(2)
        self.VA17.setObjectName("VA17")
        self.VA19 = QtGui.QLineEdit(self.centralwidget)
        self.VA19.setGeometry(QtCore.QRect(410, 548, 40, 25))
        self.VA19.setMaxLength(2)
        self.VA19.setObjectName("VA19")
        self.VB29 = QtGui.QLineEdit(self.centralwidget)
        self.VB29.setGeometry(QtCore.QRect(330, 827, 40, 25))
        self.VB29.setMaxLength(2)
        self.VB29.setObjectName("VB29")
        self.UA17 = QtGui.QLineEdit(self.centralwidget)
        self.UA17.setGeometry(QtCore.QRect(74, 493, 40, 25))
        self.UA17.setMaxLength(2)
        self.UA17.setObjectName("UA17")
        self.VA31 = QtGui.QLineEdit(self.centralwidget)
        self.VA31.setGeometry(QtCore.QRect(410, 881, 40, 25))
        self.VA31.setMaxLength(2)
        self.VA31.setObjectName("VA31")
        self.VB17 = QtGui.QLineEdit(self.centralwidget)
        self.VB17.setGeometry(QtCore.QRect(330, 493, 40, 25))
        self.VB17.setMaxLength(2)
        self.VB17.setObjectName("VB17")
        self.UA22 = QtGui.QLineEdit(self.centralwidget)
        self.UA22.setGeometry(QtCore.QRect(74, 630, 40, 25))
        self.UA22.setMaxLength(2)
        self.UA22.setObjectName("UA22")
        self.VB30 = QtGui.QLineEdit(self.centralwidget)
        self.VB30.setGeometry(QtCore.QRect(330, 854, 40, 25))
        self.VB30.setMaxLength(2)
        self.VB30.setObjectName("VB30")
        self.UB23 = QtGui.QLineEdit(self.centralwidget)
        self.UB23.setGeometry(QtCore.QRect(154, 658, 40, 25))
        self.UB23.setMaxLength(2)
        self.UB23.setObjectName("UB23")
        self.VA24 = QtGui.QLineEdit(self.centralwidget)
        self.VA24.setGeometry(QtCore.QRect(410, 686, 40, 25))
        self.VA24.setMaxLength(2)
        self.VA24.setObjectName("VA24")
        self.UB21 = QtGui.QLineEdit(self.centralwidget)
        self.UB21.setGeometry(QtCore.QRect(154, 603, 40, 25))
        self.UB21.setMaxLength(2)
        self.UB21.setObjectName("UB21")
        self.VB24 = QtGui.QLineEdit(self.centralwidget)
        self.VB24.setGeometry(QtCore.QRect(330, 686, 40, 25))
        self.VB24.setMaxLength(2)
        self.VB24.setObjectName("VB24")
        self.VB20 = QtGui.QLineEdit(self.centralwidget)
        self.VB20.setGeometry(QtCore.QRect(330, 576, 40, 25))
        self.VB20.setMaxLength(2)
        self.VB20.setObjectName("VB20")
        self.VB32 = QtGui.QLineEdit(self.centralwidget)
        self.VB32.setGeometry(QtCore.QRect(330, 909, 40, 25))
        self.VB32.setMaxLength(2)
        self.VB32.setObjectName("VB32")
        self.VB26 = QtGui.QLineEdit(self.centralwidget)
        self.VB26.setGeometry(QtCore.QRect(330, 742, 40, 25))
        self.VB26.setMaxLength(2)
        self.VB26.setObjectName("VB26")
        self.VA27 = QtGui.QLineEdit(self.centralwidget)
        self.VA27.setGeometry(QtCore.QRect(410, 770, 40, 25))
        self.VA27.setMaxLength(2)
        self.VA27.setObjectName("VA27")
        self.VB23 = QtGui.QLineEdit(self.centralwidget)
        self.VB23.setGeometry(QtCore.QRect(330, 658, 40, 25))
        self.VB23.setMaxLength(2)
        self.VB23.setObjectName("VB23")
        self.UB27 = QtGui.QLineEdit(self.centralwidget)
        self.UB27.setGeometry(QtCore.QRect(154, 770, 40, 25))
        self.UB27.setMaxLength(2)
        self.UB27.setObjectName("UB27")
        self.VB19 = QtGui.QLineEdit(self.centralwidget)
        self.VB19.setGeometry(QtCore.QRect(330, 548, 40, 25))
        self.VB19.setMaxLength(2)
        self.VB19.setObjectName("VB19")
        self.UB19 = QtGui.QLineEdit(self.centralwidget)
        self.UB19.setGeometry(QtCore.QRect(154, 548, 40, 25))
        self.UB19.setMaxLength(2)
        self.UB19.setObjectName("UB19")
        self.VA30 = QtGui.QLineEdit(self.centralwidget)
        self.VA30.setGeometry(QtCore.QRect(410, 854, 40, 25))
        self.VA30.setMaxLength(2)
        self.VA30.setObjectName("VA30")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(44, 55, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(44, 82, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(44, 136, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(44, 109, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(44, 191, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(44, 247, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(44, 220, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(44, 163, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(43, 306, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(43, 473, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(43, 389, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(43, 362, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(43, 416, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(43, 333, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(43, 445, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(46, 275, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(43, 527, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(43, 693, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(45, 916, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(43, 610, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(45, 807, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(45, 778, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(45, 834, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(43, 584, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(43, 637, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(45, 750, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(43, 555, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(43, 665, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(45, 888, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(45, 722, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(43, 500, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(45, 861, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.V_label = QtGui.QLabel(self.centralwidget)
        self.V_label.setGeometry(QtCore.QRect(381, 51, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.V_label.setFont(font)
        self.V_label.setObjectName("V_label")
        self.uLabel = QtGui.QLabel(self.centralwidget)
        self.uLabel.setGeometry(QtCore.QRect(123, 48, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.uLabel.setFont(font)
        self.uLabel.setObjectName("uLabel")
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(231, 754, 61, 27))
        self.saveButton.setObjectName("saveButton")
        self.a_label = QtGui.QLabel(self.centralwidget)
        self.a_label.setGeometry(QtCore.QRect(86, 31, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.a_label.setFont(font)
        self.a_label.setObjectName("a_label")
        self.b_label = QtGui.QLabel(self.centralwidget)
        self.b_label.setGeometry(QtCore.QRect(167, 31, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.b_label.setFont(font)
        self.b_label.setObjectName("b_label")
        self.A_label2 = QtGui.QLabel(self.centralwidget)
        self.A_label2.setGeometry(QtCore.QRect(423, 32, 22, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.A_label2.setFont(font)
        self.A_label2.setObjectName("A_label2")
        self.b_label_2 = QtGui.QLabel(self.centralwidget)
        self.b_label_2.setGeometry(QtCore.QRect(344, 31, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.b_label_2.setFont(font)
        self.b_label_2.setObjectName("b_label_2")
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(220, 44, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.ElogButton = QtGui.QPushButton(self.centralwidget)
        self.ElogButton.setEnabled(True)
        self.ElogButton.setGeometry(QtCore.QRect(206, 790, 111, 30))
        self.ElogButton.setObjectName("ElogButton")
        self.ModuleNumber = QtGui.QLineEdit(self.centralwidget)
        self.ModuleNumber.setGeometry(QtCore.QRect(238, 124, 50, 31))
        self.ModuleNumber.setMaxLength(2)
        self.ModuleNumber.setObjectName("ModuleNumber")
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(462, 81, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(463, 721, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(461, 636, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(461, 415, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(461, 664, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(461, 554, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(463, 887, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(461, 444, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(461, 361, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(461, 692, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(461, 305, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtGui.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(461, 609, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(464, 274, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtGui.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(462, 162, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtGui.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(461, 583, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtGui.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(463, 860, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtGui.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(461, 472, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtGui.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(461, 332, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(461, 526, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtGui.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(463, 806, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtGui.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(463, 833, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtGui.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(462, 135, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtGui.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(462, 190, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtGui.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(461, 499, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtGui.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(462, 246, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtGui.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(463, 749, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtGui.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(463, 915, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtGui.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(462, 219, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtGui.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(462, 54, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtGui.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(463, 777, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtGui.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(462, 108, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtGui.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(461, 388, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.TOP_2 = QtGui.QLabel(self.centralwidget)
        self.TOP_2.setGeometry(QtCore.QRect(-2, -6, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(26)
        self.TOP_2.setFont(font)
        self.TOP_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TOP_2.setObjectName("TOP_2")
        self.TOP_3 = QtGui.QLabel(self.centralwidget)
        self.TOP_3.setGeometry(QtCore.QRect(-110, 980, 781, 50))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.TOP_3.setFont(font)
        self.TOP_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TOP_3.setObjectName("TOP_3")
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(217, 74, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.CloseBtn = QtGui.QPushButton(self.centralwidget)
        self.CloseBtn.setGeometry(QtCore.QRect(216, 860, 91, 27))
        self.CloseBtn.setObjectName("CloseBtn")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(202, 840, 118, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.EmailBtn = QtGui.QPushButton(self.centralwidget)
        self.EmailBtn.setGeometry(QtCore.QRect(400, 960, 111, 27))
        self.EmailBtn.setObjectName("EmailBtn")
        self.email_box = QtGui.QLineEdit(self.centralwidget)
        self.email_box.setGeometry(QtCore.QRect(170, 960, 221, 25))
        self.email_box.setMaxLength(40)
        self.email_box.setObjectName("email_box")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(250, 230, 20, 141))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.beforeJacking = QtGui.QCheckBox(self.centralwidget)
        self.beforeJacking.setGeometry(QtCore.QRect(200, 164, 131, 21))
        self.beforeJacking.setChecked(True)
        self.beforeJacking.setObjectName("beforeJacking")
        self.afterJacking = QtGui.QCheckBox(self.centralwidget)
        self.afterJacking.setGeometry(QtCore.QRect(200, 194, 131, 21))
        self.afterJacking.setObjectName("afterJacking")
        self.label_67 = QtGui.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(200, 290, 141, 341))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(250, 560, 20, 171))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_68 = QtGui.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(13, 954, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.UA1, self.UA2)
        MainWindow.setTabOrder(self.UA2, self.UA3)
        MainWindow.setTabOrder(self.UA3, self.UA4)
        MainWindow.setTabOrder(self.UA4, self.UA5)
        MainWindow.setTabOrder(self.UA5, self.UA6)
        MainWindow.setTabOrder(self.UA6, self.UA7)
        MainWindow.setTabOrder(self.UA7, self.UA8)
        MainWindow.setTabOrder(self.UA8, self.UA9)
        MainWindow.setTabOrder(self.UA9, self.UA10)
        MainWindow.setTabOrder(self.UA10, self.UA11)
        MainWindow.setTabOrder(self.UA11, self.UA12)
        MainWindow.setTabOrder(self.UA12, self.UA13)
        MainWindow.setTabOrder(self.UA13, self.UA14)
        MainWindow.setTabOrder(self.UA14, self.UA15)
        MainWindow.setTabOrder(self.UA15, self.UA16)
        MainWindow.setTabOrder(self.UA16, self.UA17)
        MainWindow.setTabOrder(self.UA17, self.UA18)
        MainWindow.setTabOrder(self.UA18, self.UA19)
        MainWindow.setTabOrder(self.UA19, self.UA20)
        MainWindow.setTabOrder(self.UA20, self.UA21)
        MainWindow.setTabOrder(self.UA21, self.UA22)
        MainWindow.setTabOrder(self.UA22, self.UA23)
        MainWindow.setTabOrder(self.UA23, self.UA24)
        MainWindow.setTabOrder(self.UA24, self.UA25)
        MainWindow.setTabOrder(self.UA25, self.UA26)
        MainWindow.setTabOrder(self.UA26, self.UA27)
        MainWindow.setTabOrder(self.UA27, self.UA28)
        MainWindow.setTabOrder(self.UA28, self.UA29)
        MainWindow.setTabOrder(self.UA29, self.UA30)
        MainWindow.setTabOrder(self.UA30, self.UA31)
        MainWindow.setTabOrder(self.UA31, self.UA32)
        MainWindow.setTabOrder(self.UA32, self.UB1)
        MainWindow.setTabOrder(self.UB1, self.UB2)
        MainWindow.setTabOrder(self.UB2, self.UB3)
        MainWindow.setTabOrder(self.UB3, self.UB4)
        MainWindow.setTabOrder(self.UB4, self.UB5)
        MainWindow.setTabOrder(self.UB5, self.UB6)
        MainWindow.setTabOrder(self.UB6, self.UB7)
        MainWindow.setTabOrder(self.UB7, self.UB8)
        MainWindow.setTabOrder(self.UB8, self.UB9)
        MainWindow.setTabOrder(self.UB9, self.UB10)
        MainWindow.setTabOrder(self.UB10, self.UB11)
        MainWindow.setTabOrder(self.UB11, self.UB12)
        MainWindow.setTabOrder(self.UB12, self.UB13)
        MainWindow.setTabOrder(self.UB13, self.UB14)
        MainWindow.setTabOrder(self.UB14, self.UB15)
        MainWindow.setTabOrder(self.UB15, self.UB16)
        MainWindow.setTabOrder(self.UB16, self.UB17)
        MainWindow.setTabOrder(self.UB17, self.UB18)
        MainWindow.setTabOrder(self.UB18, self.UB19)
        MainWindow.setTabOrder(self.UB19, self.UB20)
        MainWindow.setTabOrder(self.UB20, self.UB21)
        MainWindow.setTabOrder(self.UB21, self.UB22)
        MainWindow.setTabOrder(self.UB22, self.UB23)
        MainWindow.setTabOrder(self.UB23, self.UB24)
        MainWindow.setTabOrder(self.UB24, self.UB25)
        MainWindow.setTabOrder(self.UB25, self.UB26)
        MainWindow.setTabOrder(self.UB26, self.UB27)
        MainWindow.setTabOrder(self.UB27, self.UB28)
        MainWindow.setTabOrder(self.UB28, self.UB29)
        MainWindow.setTabOrder(self.UB29, self.UB30)
        MainWindow.setTabOrder(self.UB30, self.UB31)
        MainWindow.setTabOrder(self.UB31, self.UB32)
        MainWindow.setTabOrder(self.UB32, self.VB1)
        MainWindow.setTabOrder(self.VB1, self.VB2)
        MainWindow.setTabOrder(self.VB2, self.VB3)
        MainWindow.setTabOrder(self.VB3, self.VB4)
        MainWindow.setTabOrder(self.VB4, self.VB5)
        MainWindow.setTabOrder(self.VB5, self.VB6)
        MainWindow.setTabOrder(self.VB6, self.VB7)
        MainWindow.setTabOrder(self.VB7, self.VB8)
        MainWindow.setTabOrder(self.VB8, self.VB9)
        MainWindow.setTabOrder(self.VB9, self.VB10)
        MainWindow.setTabOrder(self.VB10, self.VB11)
        MainWindow.setTabOrder(self.VB11, self.VB12)
        MainWindow.setTabOrder(self.VB12, self.VB13)
        MainWindow.setTabOrder(self.VB13, self.VB14)
        MainWindow.setTabOrder(self.VB14, self.VB15)
        MainWindow.setTabOrder(self.VB15, self.VB16)
        MainWindow.setTabOrder(self.VB16, self.VB17)
        MainWindow.setTabOrder(self.VB17, self.VB18)
        MainWindow.setTabOrder(self.VB18, self.VB19)
        MainWindow.setTabOrder(self.VB19, self.VB20)
        MainWindow.setTabOrder(self.VB20, self.VB21)
        MainWindow.setTabOrder(self.VB21, self.VB22)
        MainWindow.setTabOrder(self.VB22, self.VB23)
        MainWindow.setTabOrder(self.VB23, self.VB24)
        MainWindow.setTabOrder(self.VB24, self.VB25)
        MainWindow.setTabOrder(self.VB25, self.VB26)
        MainWindow.setTabOrder(self.VB26, self.VB27)
        MainWindow.setTabOrder(self.VB27, self.VB28)
        MainWindow.setTabOrder(self.VB28, self.VB29)
        MainWindow.setTabOrder(self.VB29, self.VB30)
        MainWindow.setTabOrder(self.VB30, self.VB31)
        MainWindow.setTabOrder(self.VB31, self.VB32)
        MainWindow.setTabOrder(self.VB32, self.VA1)
        MainWindow.setTabOrder(self.VA1, self.VA2)
        MainWindow.setTabOrder(self.VA2, self.VA3)
        MainWindow.setTabOrder(self.VA3, self.VA4)
        MainWindow.setTabOrder(self.VA4, self.VA5)
        MainWindow.setTabOrder(self.VA5, self.VA6)
        MainWindow.setTabOrder(self.VA6, self.VA7)
        MainWindow.setTabOrder(self.VA7, self.VA8)
        MainWindow.setTabOrder(self.VA8, self.VA9)
        MainWindow.setTabOrder(self.VA9, self.VA10)
        MainWindow.setTabOrder(self.VA10, self.VA11)
        MainWindow.setTabOrder(self.VA11, self.VA12)
        MainWindow.setTabOrder(self.VA12, self.VA13)
        MainWindow.setTabOrder(self.VA13, self.VA14)
        MainWindow.setTabOrder(self.VA14, self.VA15)
        MainWindow.setTabOrder(self.VA15, self.VA16)
        MainWindow.setTabOrder(self.VA16, self.VA17)
        MainWindow.setTabOrder(self.VA17, self.VA18)
        MainWindow.setTabOrder(self.VA18, self.VA19)
        MainWindow.setTabOrder(self.VA19, self.VA20)
        MainWindow.setTabOrder(self.VA20, self.VA21)
        MainWindow.setTabOrder(self.VA21, self.VA22)
        MainWindow.setTabOrder(self.VA22, self.VA23)
        MainWindow.setTabOrder(self.VA23, self.VA24)
        MainWindow.setTabOrder(self.VA24, self.VA25)
        MainWindow.setTabOrder(self.VA25, self.VA26)
        MainWindow.setTabOrder(self.VA26, self.VA27)
        MainWindow.setTabOrder(self.VA27, self.VA28)
        MainWindow.setTabOrder(self.VA28, self.VA29)
        MainWindow.setTabOrder(self.VA29, self.VA30)
        MainWindow.setTabOrder(self.VA30, self.VA31)
        MainWindow.setTabOrder(self.VA31, self.VA32)
        MainWindow.setTabOrder(self.VA32, self.ModuleNumber)
        MainWindow.setTabOrder(self.ModuleNumber, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.ElogButton)
        MainWindow.setTabOrder(self.ElogButton, self.CloseBtn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.UA1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB8.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB8.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA8.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA8.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB12.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB14.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA12.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB13.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA13.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB9.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA9.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA10.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB11.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB10.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA15.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA15.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA11.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA16.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB13.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA16.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB11.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA14.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB16.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA11.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB15.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB9.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB16.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA9.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA13.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA12.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA14.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA10.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB14.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB15.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB10.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB12.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA21.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA26.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB32.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA32.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB21.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB25.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB22.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB17.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB25.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA25.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB29.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA28.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA23.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA20.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB18.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA23.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB24.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB20.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA29.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA19.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB31.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB30.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB28.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB27.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA27.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA28.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA29.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA25.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA24.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB18.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA26.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA20.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA18.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA31.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA32.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB31.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB28.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA21.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA22.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB22.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA30.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB26.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA18.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA17.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA19.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB29.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA17.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA31.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB17.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UA22.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB30.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB23.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA24.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB21.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB24.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB20.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB32.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB26.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA27.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB23.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB27.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VB19.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.UB19.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.VA30.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "31", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.V_label.setText(QtGui.QApplication.translate("MainWindow", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.uLabel.setText(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.a_label.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.b_label.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.A_label2.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.b_label_2.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Module ", None, QtGui.QApplication.UnicodeUTF8))
        self.ElogButton.setText(QtGui.QApplication.translate("MainWindow", "Send To Elog", None, QtGui.QApplication.UnicodeUTF8))
        self.ModuleNumber.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "31", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.TOP_2.setText(QtGui.QApplication.translate("MainWindow", "Tension Test Recorder", None, QtGui.QApplication.UnicodeUTF8))
        self.TOP_3.setText(QtGui.QApplication.translate("MainWindow", "More info @ http://hep.ph.liv.ac.uk/~wturner/Recorders.html", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.CloseBtn.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.EmailBtn.setText(QtGui.QApplication.translate("MainWindow", "Email Data", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeJacking.setText(QtGui.QApplication.translate("MainWindow", "Before Jacking", None, QtGui.QApplication.UnicodeUTF8))
        self.afterJacking.setText(QtGui.QApplication.translate("MainWindow", "After Jacking", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Enter Data \n"
"Click Save\n"
"Then\n"
"Send To Elog\n"
"  or \n"
"Email Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Email Address :", None, QtGui.QApplication.UnicodeUTF8))

